name: Check project
run-name: ${{ github.actor }} is updating main branches🚀
on:
  push:
    branches:
      - 'master'
      - 'dev'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm i
      - name: Lint check
        run: npm run lint
  ts-check:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install deps
        run: npm i
      - name: Typescript check
        run: npm run ts-check
